import { Parable } from './types';

export const parables: Parable[] = [
  {
    id: 'good-samaritan',
    title: 'The Good Samaritan',
    reference: 'Luke 10:25-37',
    summary: 'A Samaritan helps a beaten traveler ignored by a priest and a Levite, teaching that true neighborliness crosses all boundaries.',
    fullText: 'A man was going down from Jerusalem to Jericho, when he was attacked by robbers. They stripped him of his clothes, beat him and went away, leaving him half dead. A priest happened to be going down the same road, and when he saw the man, he passed by on the other side. So too, a Levite, when he came to the place and saw him, passed by on the other side. But a Samaritan, as he traveled, came where the man was; and when he saw him, he took pity on him. He went to him and bandaged his wounds, pouring on oil and wine. Then he put the man on his own donkey, brought him to an inn and took care of him.',
    themes: ['compassion', 'neighbor', 'mercy', 'love'],
    suggestPrompt: 'What does the Parable of the Good Samaritan teach us about loving our neighbor?',
  },
  {
    id: 'prodigal-son',
    title: 'The Prodigal Son',
    reference: 'Luke 15:11-32',
    summary: 'A wayward son squanders his inheritance but is welcomed home with open arms by his loving father, illustrating God\'s boundless forgiveness.',
    fullText: 'There was a man who had two sons. The younger one said to his father, "Father, give me my share of the estate." So he divided his property between them. Not long after that, the younger son got together all he had, set off for a distant country and there squandered his wealth in wild living. After he had spent everything, there was a severe famine in that whole country, and he began to be in need. When he came to his senses, he said, "I will set out and go back to my father and say to him: Father, I have sinned against heaven and against you." But while he was still a long way off, his father saw him and was filled with compassion for him; he ran to his son, threw his arms around him and kissed him.',
    themes: ['forgiveness', 'repentance', 'grace', 'love'],
    suggestPrompt: 'What does the Parable of the Prodigal Son teach about forgiveness and grace?',
  },
  {
    id: 'sower',
    title: 'The Sower',
    reference: 'Matthew 13:1-23',
    summary: 'A farmer scatters seed on different types of soil, representing how people receive and respond to God\'s word differently.',
    fullText: 'A farmer went out to sow his seed. As he was scattering the seed, some fell along the path, and the birds came and ate it up. Some fell on rocky places, where it did not have much soil. It sprang up quickly, because the soil was shallow. But when the sun came up, the plants were scorched, and they withered because they had no root. Other seed fell among thorns, which grew up and choked the plants. Still other seed fell on good soil, where it produced a crop — a hundred, sixty or thirty times what was sown.',
    themes: ['faith', 'growth', 'perseverance', 'wisdom'],
    suggestPrompt: 'What does the Parable of the Sower teach about receiving wisdom?',
  },
  {
    id: 'mustard-seed',
    title: 'The Mustard Seed',
    reference: 'Matthew 13:31-32',
    summary: 'The smallest of seeds grows into the largest garden plant, showing that great things can grow from humble beginnings.',
    fullText: 'The kingdom of heaven is like a mustard seed, which a man took and planted in his field. Though it is the smallest of all seeds, yet when it grows, it is the largest of garden plants and becomes a tree, so that the birds come and perch in its branches.',
    themes: ['faith', 'growth', 'hope', 'patience'],
    suggestPrompt: 'How does the Mustard Seed parable encourage us when our faith feels small?',
  },
  {
    id: 'lost-sheep',
    title: 'The Lost Sheep',
    reference: 'Luke 15:1-7',
    summary: 'A shepherd leaves ninety-nine sheep to find the one that is lost, showing that every individual matters deeply.',
    fullText: 'Suppose one of you has a hundred sheep and loses one of them. Doesn\'t he leave the ninety-nine in the open country and go after the lost sheep until he finds it? And when he finds it, he joyfully puts it on his shoulders and goes home. Then he calls his friends and neighbors together and says, "Rejoice with me; I have found my lost sheep."',
    themes: ['love', 'compassion', 'seeking', 'joy'],
    suggestPrompt: 'What does the Parable of the Lost Sheep teach about how much each person matters?',
  },
  {
    id: 'talents',
    title: 'The Talents',
    reference: 'Matthew 25:14-30',
    summary: 'A master entrusts his servants with talents; those who invest wisely are rewarded, teaching us to use our gifts faithfully.',
    fullText: 'A man going on a journey called his servants and entrusted his wealth to them. To one he gave five bags of gold, to another two bags, and to another one bag, each according to his ability. The man who had received five bags of gold went at once and put his money to work and gained five bags more. So also, the one with two bags gained two more. But the man who had received one bag went off, dug a hole in the ground and hid his master\'s money. After a long time the master returned and settled accounts with them.',
    themes: ['stewardship', 'faithfulness', 'courage', 'growth'],
    suggestPrompt: 'What does the Parable of the Talents teach about using our gifts?',
  },
  {
    id: 'good-shepherd',
    title: 'The Good Shepherd',
    reference: 'John 10:1-18',
    summary: 'Jesus describes himself as the good shepherd who lays down his life for the sheep, teaching about sacrificial love and care.',
    fullText: 'I am the good shepherd. The good shepherd lays down his life for the sheep. The hired hand is not the shepherd and does not own the sheep. So when he sees the wolf coming, he abandons the sheep and runs away. Then the wolf attacks the flock and scatters it. I am the good shepherd; I know my sheep and my sheep know me — just as the Father knows me and I know the Father — and I lay down my life for the sheep.',
    themes: ['love', 'sacrifice', 'protection', 'trust'],
    suggestPrompt: 'What does it mean that Jesus is the Good Shepherd?',
  },
  {
    id: 'rich-fool',
    title: 'The Rich Fool',
    reference: 'Luke 12:13-21',
    summary: 'A wealthy man builds bigger barns to store his abundance but dies that night, teaching about the folly of material obsession.',
    fullText: 'The ground of a certain rich man yielded an abundant harvest. He thought to himself, "What shall I do? I have no place to store my crops." Then he said, "This is what I\'ll do. I will tear down my barns and build bigger ones, and there I will store my surplus grain. And I\'ll say to myself, You have plenty of grain laid up for many years. Take life easy; eat, drink and be merry." But God said to him, "You fool! This very night your life will be demanded from you. Then who will get what you have prepared for yourself?" This is how it will be with whoever stores up things for themselves but is not rich toward God.',
    themes: ['wisdom', 'humility', 'generosity', 'priorities'],
    suggestPrompt: 'What does the Parable of the Rich Fool teach about what truly matters in life?',
  },
  {
    id: 'pharisee-tax-collector',
    title: 'The Pharisee and the Tax Collector',
    reference: 'Luke 18:9-14',
    summary: 'A humble tax collector\'s prayer is honored over a proud Pharisee\'s, teaching that humility before God matters more than outward righteousness.',
    fullText: 'Two men went up to the temple to pray, one a Pharisee and the other a tax collector. The Pharisee stood by himself and prayed: "God, I thank you that I am not like other people — robbers, evildoers, adulterers — or even like this tax collector." But the tax collector stood at a distance. He would not even look up to heaven, but beat his breast and said, "God, have mercy on me, a sinner." I tell you that this man, rather than the other, went home justified before God. For all those who exalt themselves will be humbled, and those who humble themselves will be exalted.',
    themes: ['humility', 'prayer', 'grace', 'repentance'],
    suggestPrompt: 'What does the Parable of the Pharisee and Tax Collector teach about humility?',
  },
  {
    id: 'unforgiving-servant',
    title: 'The Unforgiving Servant',
    reference: 'Matthew 18:21-35',
    summary: 'A servant forgiven a massive debt refuses to forgive a small debt owed to him, teaching that we must forgive as we have been forgiven.',
    fullText: 'The kingdom of heaven is like a king who wanted to settle accounts with his servants. As he began the settlement, a man who owed him ten thousand bags of gold was brought to him. Since he was not able to pay, the master ordered that he and his wife and his children and all that he had be sold to repay the debt. At this the servant fell on his knees before him. "Be patient with me," he begged, "and I will pay back everything." The servant\'s master took pity on him, canceled the debt and let him go. But when that servant went out, he found one of his fellow servants who owed him a hundred silver coins. He grabbed him and began to choke him. "Pay back what you owe me!" he demanded.',
    themes: ['forgiveness', 'mercy', 'gratitude', 'compassion'],
    suggestPrompt: 'What does the Parable of the Unforgiving Servant teach about forgiveness?',
  },
  {
    id: 'wedding-banquet',
    title: 'The Wedding Banquet',
    reference: 'Matthew 22:1-14',
    summary: 'A king invites guests to a wedding feast, but those invited refuse to come, so he opens the invitation to everyone.',
    fullText: 'The kingdom of heaven is like a king who prepared a wedding banquet for his son. He sent his servants to those who had been invited to the banquet to tell them to come, but they refused to come. Then he sent some more servants and said, "Tell those who have been invited that I have prepared my dinner." But they paid no attention and went off — one to his field, another to his business. Then he said to his servants, "Go to the street corners and invite to the banquet anyone you find." So the servants went out into the streets and gathered all the people they could find, the bad as well as the good, and the wedding hall was filled with guests.',
    themes: ['grace', 'invitation', 'readiness', 'gratitude'],
    suggestPrompt: 'What does the Wedding Banquet parable teach about being open to grace?',
  },
  {
    id: 'pearl-of-great-price',
    title: 'The Pearl of Great Price',
    reference: 'Matthew 13:45-46',
    summary: 'A merchant finds a pearl of extraordinary value and sells everything to possess it, teaching about the supreme worth of the kingdom of heaven.',
    fullText: 'Again, the kingdom of heaven is like a merchant looking for fine pearls. When he found one of great value, he went away and sold everything he had and bought it.',
    themes: ['faith', 'priorities', 'devotion', 'wisdom'],
    suggestPrompt: 'What is the "pearl of great price" and what must we give to find it?',
  },
  {
    id: 'fig-tree',
    title: 'The Barren Fig Tree',
    reference: 'Luke 13:6-9',
    summary: 'A fig tree given one more year to bear fruit, teaching about patience, second chances, and the importance of bearing fruit.',
    fullText: 'A man had a fig tree growing in his vineyard, and he went to look for fruit on it but did not find any. So he said to the man who took care of the vineyard, "For three years now I\'ve been coming to look for fruit on this fig tree and haven\'t found any. Cut it down! Why should it use up the soil?" "Sir," the man replied, "leave it alone for one more year, and I\'ll dig around it and fertilize it. If it bears fruit next year, fine! If not, then cut it down."',
    themes: ['patience', 'growth', 'repentance', 'grace'],
    suggestPrompt: 'What does the Barren Fig Tree teach about patience and second chances?',
  },
  {
    id: 'house-on-rock',
    title: 'The Wise and Foolish Builders',
    reference: 'Matthew 7:24-27',
    summary: 'One man builds on rock, another on sand — when storms come, only the house on rock stands, teaching about the importance of a strong foundation.',
    fullText: 'Everyone who hears these words of mine and puts them into practice is like a wise man who built his house on the rock. The rain came down, the streams rose, and the winds blew and beat against that house; yet it did not fall, because it had its foundation on the rock. But everyone who hears these words of mine and does not put them into practice is like a foolish man who built his house on sand. The rain came down, the streams rose, and the winds blew and beat against that house, and it fell with a great crash.',
    themes: ['wisdom', 'faith', 'perseverance', 'foundation'],
    suggestPrompt: 'How can we build our lives on a strong foundation like the wise builder?',
  },
  {
    id: 'ten-virgins',
    title: 'The Ten Virgins',
    reference: 'Matthew 25:1-13',
    summary: 'Five wise virgins keep oil for their lamps while five foolish ones do not, teaching about being prepared and watchful.',
    fullText: 'The kingdom of heaven will be like ten virgins who took their lamps and went out to meet the bridegroom. Five of them were foolish and five were wise. The foolish ones took their lamps but did not take any oil with them. The wise ones, however, took oil in jars along with their lamps. The bridegroom was a long time in coming, and they all became drowsy and fell asleep. At midnight the cry rang out: "Here\'s the bridegroom! Come out to meet him!" Then all the virgins woke up and trimmed their lamps. The foolish ones said to the wise, "Give us some of your oil; our lamps are going out."',
    themes: ['readiness', 'wisdom', 'faithfulness', 'preparation'],
    suggestPrompt: 'What does the Parable of the Ten Virgins teach about being spiritually prepared?',
  },
];
